### ISSUE TITLE
Do these save files work directly in retroarch?

### ISSUE THREAD

**Issue by justinmcrp** [madmodder123/retropie_saves#2]
I see there's a multitude of file formats listed amongst the files (I'm looking at N64 in particular.)

Do these need conversion to SRM or anything before using on a retropie/retroarch?

**Comment by madmodder123** [comment]
RetroArch N64 emulators run like garbage on the Raspberry Pi so only the raw cartridge/memory card saves are provided for the non-Libretro emulators (aka mupen64plus).
Just put the saves in the same directory as the ROMs and make sure they have the same name as the ROM and you should be good to go :)
